# Generated by Django 3.2.11 on 2022-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default='defualt.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
